#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

# Set default Postgres user if not provided
if [ -z "${POSTGRES_USER:-}" ]; then 
    base_postgres_image_default_user='postgres'
    export POSTGRES_USER="${base_postgres_image_default_user}"
fi 

# Construct the DATABASE_URL environment variable
export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

# Wait for PostgreSQL to be available
python << END
import sys 
import time 
import psycopg2

suggest_unrecoverable_after = 30
start = time.time()

while True:
    try:
        conn = psycopg2.connect(
            dbname="${POSTGRES_DB}",
            user="${POSTGRES_USER}",
            password="${POSTGRES_PASSWORD}",
            host="${POSTGRES_HOST}",
            port="${POSTGRES_PORT}",
        )
        conn.close()
        print("PostgreSQL is available.")
        break 
    except psycopg2.OperationalError as e:
        sys.stderr.write("Waiting for PostgreSQL to be available...\n")
        if time.time() - start > suggest_unrecoverable_after:
            sys.stderr.write(f"This is taking longer than expected and may be due to an unrecoverable error: {str(e)}\n")
            break 
        time.sleep(1)
END

>&2 echo "PostgreSQL is available."

exec "$@"
